insert into development.registration_numbers (reg_num, town_code) values ('CA 123-456', 'CA');
insert into development.registration_numbers (reg_num, town_code) values ('CZ 567890', 'CZ');
insert into development.registration_numbers (reg_num, town_code) values ('CG5678-90', 'CG');
insert into development.registration_numbers (reg_num, town_code) values ('CF 56 90', 'CF');
insert into development.registration_numbers (reg_num, town_code) values ('CX 000-007', 'CX');
insert into development.registration_numbers (reg_num, town_code) values ('CA 32-6490', 'CA');
insert into development.registration_numbers (reg_num, town_code) values ('CX240690', 'CX');
insert into development.registration_numbers (reg_num, town_code) values ('CA 01', 'CA');
insert into development.registration_numbers (reg_num, town_code) values ('CG 500-0', 'CG');
insert into development.registration_numbers (reg_num, town_code) values ('CG 234 234', 'CG');
insert into development.registration_numbers (reg_num, town_code) values ('CG6344', 'CG');
insert into development.registration_numbers (reg_num, town_code) values ('CA 987-210', 'CA');
insert into development.registration_numbers (reg_num, town_code) values ('CZ 999', 'CZ');
insert into development.registration_numbers (reg_num, town_code) values ('CK 12-3406', 'CK');
insert into development.registration_numbers (reg_num, town_code) values ('CA123-456', 'CA');
insert into development.registration_numbers (reg_num, town_code) values ('CY 770-007', 'CY');