insert into test.towns (town_code, town_name, selected) values ('CA', 'Cape Town', false);
insert into test.towns (town_code, town_name, selected) values ('CF', 'Kuils River', false);
insert into test.towns (town_code, town_name, selected) values ('CG', 'Oudtshoorn', false);
insert into test.towns (town_code, town_name, selected) values ('CJ', 'Paarl', false);
insert into test.towns (town_code, town_name, selected) values ('CK', 'Malmesbury', false);
insert into test.towns (town_code, town_name, selected) values ('CL', 'Stellenbosch', false);
insert into test.towns (town_code, town_name, selected) values ('CN', 'Wellington', false);
insert into test.towns (town_code, town_name, selected) values ('CO', 'Calitzdorp', false);
insert into test.towns (town_code, town_name, selected) values ('CR', 'Hopefield', false);
insert into test.towns (town_code, town_name, selected) values ('CT', 'Ceres', false);
insert into test.towns (town_code, town_name, selected) values ('CV', 'Vredendal', false);
insert into test.towns (town_code, town_name, selected) values ('CW', 'Worcester', false);
insert into test.towns (town_code, town_name, selected) values ('CX', 'Knysna', false);
insert into test.towns (town_code, town_name, selected) values ('CY', 'Bellville', false);
insert into test.towns (town_code, town_name, selected) values ('CZ', 'Beaufort West', false);

insert into development.towns (town_code, town_name, selected) values ('CA', 'Cape Town', false);
insert into development.towns (town_code, town_name, selected) values ('CF', 'Kuils River', false);
insert into development.towns (town_code, town_name, selected) values ('CG', 'Oudtshoorn', false);
insert into development.towns (town_code, town_name, selected) values ('CJ', 'Paarl', false);
insert into development.towns (town_code, town_name, selected) values ('CK', 'Malmesbury', false);
insert into development.towns (town_code, town_name, selected) values ('CL', 'Stellenbosch', false);
insert into development.towns (town_code, town_name, selected) values ('CN', 'Wellington', false);
insert into development.towns (town_code, town_name, selected) values ('CO', 'Calitzdorp', false);
insert into development.towns (town_code, town_name, selected) values ('CR', 'Hopefield', false);
insert into development.towns (town_code, town_name, selected) values ('CT', 'Ceres', false);
insert into development.towns (town_code, town_name, selected) values ('CV', 'Vredendal', false);
insert into development.towns (town_code, town_name, selected) values ('CW', 'Worcester', false);
insert into development.towns (town_code, town_name, selected) values ('CX', 'Knysna', false);
insert into development.towns (town_code, town_name, selected) values ('CY', 'Bellville', false);
insert into development.towns (town_code, town_name, selected) values ('CZ', 'Beaufort West', false);

insert into production.towns (town_code, town_name, selected) values ('CA', 'Cape Town', false);
insert into production.towns (town_code, town_name, selected) values ('CF', 'Kuils River', false);
insert into production.towns (town_code, town_name, selected) values ('CG', 'Oudtshoorn', false);
insert into production.towns (town_code, town_name, selected) values ('CJ', 'Paarl', false);
insert into production.towns (town_code, town_name, selected) values ('CK', 'Malmesbury', false);
insert into production.towns (town_code, town_name, selected) values ('CL', 'Stellenbosch', false);
insert into production.towns (town_code, town_name, selected) values ('CN', 'Wellington', false);
insert into production.towns (town_code, town_name, selected) values ('CO', 'Calitzdorp', false);
insert into production.towns (town_code, town_name, selected) values ('CR', 'Hopefield', false);
insert into production.towns (town_code, town_name, selected) values ('CT', 'Ceres', false);
insert into production.towns (town_code, town_name, selected) values ('CV', 'Vredendal', false);
insert into production.towns (town_code, town_name, selected) values ('CW', 'Worcester', false);
insert into production.towns (town_code, town_name, selected) values ('CX', 'Knysna', false);
insert into production.towns (town_code, town_name, selected) values ('CY', 'Bellville', false);
insert into production.towns (town_code, town_name, selected) values ('CZ', 'Beaufort West', false);



insert into test.towns (town_code, town_name, selected) values ('CAM', 'Caledon', false);
insert into test.towns (town_code, town_name, selected) values ('CAR', 'Clanwilliam', false);
insert into test.towns (town_code, town_name, selected) values ('CAW', 'George', false);
insert into test.towns (town_code, town_name, selected) values ('CBL', 'Ladismith', false);
insert into test.towns (town_code, town_name, selected) values ('CBM', 'Laingsburg', false);
insert into test.towns (town_code, town_name, selected) values ('CBR', 'Montagu', false);
insert into test.towns (town_code, town_name, selected) values ('CBS', 'Mossel Bay', false);
insert into test.towns (town_code, town_name, selected) values ('CBT', 'Murraysburg', false);
insert into test.towns (town_code, town_name, selected) values ('CBY', 'Piketburg', false);
insert into test.towns (town_code, town_name, selected) values ('CCA', 'Prince Albert', false);
insert into test.towns (town_code, town_name, selected) values ('CCC', 'Riversdale', false);
insert into test.towns (town_code, town_name, selected) values ('CCD', 'Robertson', false);
insert into test.towns (town_code, town_name, selected) values ('CCK', 'Swellendam', false);
insert into test.towns (town_code, town_name, selected) values ('CCM', 'Tulbagh', false);
insert into test.towns (town_code, town_name, selected) values ('CCO', 'Uniondale', false);
insert into test.towns (town_code, town_name, selected) values ('CCP', 'Vanrhydorp', false);
insert into test.towns (town_code, town_name, selected) values ('CEA', 'Moorreesburg', false);
insert into test.towns (town_code, town_name, selected) values ('CEG', 'Heidelberg', false);
insert into test.towns (town_code, town_name, selected) values ('CEM', 'Hermanus', false);
insert into test.towns (town_code, town_name, selected) values ('CEO', 'Grabouw', false);
insert into test.towns (town_code, town_name, selected) values ('CER', 'Bonnievale', false);
insert into test.towns (town_code, town_name, selected) values ('CES', 'Albertina', false);
insert into test.towns (town_code, town_name, selected) values ('CEX', 'Porterville', false);
insert into test.towns (town_code, town_name, selected) values ('CEY', 'Strand', false);
insert into test.towns (town_code, town_name, selected) values ('CFA', 'Wolseley', false);
insert into test.towns (town_code, town_name, selected) values ('CFG', 'Vredenburg', false);
insert into test.towns (town_code, town_name, selected) values ('CFM', 'Somerset West', false);
insert into test.towns (town_code, town_name, selected) values ('CFP', 'Velddrif', false);
insert into test.towns (town_code, town_name, selected) values ('CFR', 'Brackenfell', false);
insert into test.towns (town_code, town_name, selected) values ('CCT', 'City of Cape Town Municipal', false);

insert into development.towns (town_code, town_name, selected) values ('CAM', 'Caledon', false);
insert into development.towns (town_code, town_name, selected) values ('CAR', 'Clanwilliam', false);
insert into development.towns (town_code, town_name, selected) values ('CAW', 'George', false);
insert into development.towns (town_code, town_name, selected) values ('CBL', 'Ladismith', false);
insert into development.towns (town_code, town_name, selected) values ('CBM', 'Laingsburg', false);
insert into development.towns (town_code, town_name, selected) values ('CBR', 'Montagu', false);
insert into development.towns (town_code, town_name, selected) values ('CBS', 'Mossel Bay', false);
insert into development.towns (town_code, town_name, selected) values ('CBT', 'Murraysburg', false);
insert into development.towns (town_code, town_name, selected) values ('CBY', 'Piketburg', false);
insert into development.towns (town_code, town_name, selected) values ('CCA', 'Prince Albert', false);
insert into development.towns (town_code, town_name, selected) values ('CCC', 'Riversdale', false);
insert into development.towns (town_code, town_name, selected) values ('CCD', 'Robertson', false);
insert into development.towns (town_code, town_name, selected) values ('CCK', 'Swellendam', false);
insert into development.towns (town_code, town_name, selected) values ('CCM', 'Tulbagh', false);
insert into development.towns (town_code, town_name, selected) values ('CCO', 'Uniondale', false);
insert into development.towns (town_code, town_name, selected) values ('CCP', 'Vanrhydorp', false);
insert into development.towns (town_code, town_name, selected) values ('CEA', 'Moorreesburg', false);
insert into development.towns (town_code, town_name, selected) values ('CEG', 'Heidelberg', false);
insert into development.towns (town_code, town_name, selected) values ('CEM', 'Hermanus', false);
insert into development.towns (town_code, town_name, selected) values ('CEO', 'Grabouw', false);
insert into development.towns (town_code, town_name, selected) values ('CER', 'Bonnievale', false);
insert into development.towns (town_code, town_name, selected) values ('CES', 'Albertina', false);
insert into development.towns (town_code, town_name, selected) values ('CEX', 'Porterville', false);
insert into development.towns (town_code, town_name, selected) values ('CEY', 'Strand', false);
insert into development.towns (town_code, town_name, selected) values ('CFA', 'Wolseley', false);
insert into development.towns (town_code, town_name, selected) values ('CFG', 'Vredenburg', false);
insert into development.towns (town_code, town_name, selected) values ('CFM', 'Somerset West', false);
insert into development.towns (town_code, town_name, selected) values ('CFP', 'Velddrif', false);
insert into development.towns (town_code, town_name, selected) values ('CFR', 'Brackenfell', false);
insert into development.towns (town_code, town_name, selected) values ('CCT', 'City of Cape Town Municipal', false);

insert into production.towns (town_code, town_name, selected) values ('CAM', 'Caledon', false);
insert into production.towns (town_code, town_name, selected) values ('CAR', 'Clanwilliam', false);
insert into production.towns (town_code, town_name, selected) values ('CAW', 'George', false);
insert into production.towns (town_code, town_name, selected) values ('CBL', 'Ladismith', false);
insert into production.towns (town_code, town_name, selected) values ('CBM', 'Laingsburg', false);
insert into production.towns (town_code, town_name, selected) values ('CBR', 'Montagu', false);
insert into production.towns (town_code, town_name, selected) values ('CBS', 'Mossel Bay', false);
insert into production.towns (town_code, town_name, selected) values ('CBT', 'Murraysburg', false);
insert into production.towns (town_code, town_name, selected) values ('CBY', 'Piketburg', false);
insert into production.towns (town_code, town_name, selected) values ('CCA', 'Prince Albert', false);
insert into production.towns (town_code, town_name, selected) values ('CCC', 'Riversdale', false);
insert into production.towns (town_code, town_name, selected) values ('CCD', 'Robertson', false);
insert into production.towns (town_code, town_name, selected) values ('CCK', 'Swellendam', false);
insert into production.towns (town_code, town_name, selected) values ('CCM', 'Tulbagh', false);
insert into production.towns (town_code, town_name, selected) values ('CCO', 'Uniondale', false);
insert into production.towns (town_code, town_name, selected) values ('CCP', 'Vanrhydorp', false);
insert into production.towns (town_code, town_name, selected) values ('CEA', 'Moorreesburg', false);
insert into production.towns (town_code, town_name, selected) values ('CEG', 'Heidelberg', false);
insert into production.towns (town_code, town_name, selected) values ('CEM', 'Hermanus', false);
insert into production.towns (town_code, town_name, selected) values ('CEO', 'Grabouw', false);
insert into production.towns (town_code, town_name, selected) values ('CER', 'Bonnievale', false);
insert into production.towns (town_code, town_name, selected) values ('CES', 'Albertina', false);
insert into production.towns (town_code, town_name, selected) values ('CEX', 'Porterville', false);
insert into production.towns (town_code, town_name, selected) values ('CEY', 'Strand', false);
insert into production.towns (town_code, town_name, selected) values ('CFA', 'Wolseley', false);
insert into production.towns (town_code, town_name, selected) values ('CFG', 'Vredenburg', false);
insert into production.towns (town_code, town_name, selected) values ('CFM', 'Somerset West', false);
insert into production.towns (town_code, town_name, selected) values ('CFP', 'Velddrif', false);
insert into production.towns (town_code, town_name, selected) values ('CFR', 'Brackenfell', false);
insert into production.towns (town_code, town_name, selected) values ('CCT', 'City of Cape Town Municipal', false);