insert into test.towns (town_code, town_name) values ('CA', 'Cape Town');
insert into test.towns (town_code, town_name) values ('CF', 'Kuils River');
insert into test.towns (town_code, town_name) values ('CG', 'Oudtshoorn');
insert into test.towns (town_code, town_name) values ('CJ', 'Paarl');
insert into test.towns (town_code, town_name) values ('CK', 'Malmesbury');
insert into test.towns (town_code, town_name) values ('CL', 'Stellenbosch');
insert into test.towns (town_code, town_name) values ('CN', 'Wellington');
insert into test.towns (town_code, town_name) values ('CO', 'Calitzdorp');
insert into test.towns (town_code, town_name) values ('CR', 'Hopefield');
insert into test.towns (town_code, town_name) values ('CT', 'Ceres');
insert into test.towns (town_code, town_name) values ('CV', 'Vredendal');
insert into test.towns (town_code, town_name) values ('CW', 'Worcester');
insert into test.towns (town_code, town_name) values ('CX', 'Knysna');
insert into test.towns (town_code, town_name) values ('CY', 'Bellville');
insert into test.towns (town_code, town_name) values ('CZ', 'Beaufort West');

insert into test.towns (town_code, town_name) values ('CAM', 'Caledon');
insert into test.towns (town_code, town_name) values ('CAR', 'Clanwilliam');
insert into test.towns (town_code, town_name) values ('CAW', 'George');
insert into test.towns (town_code, town_name) values ('CBL', 'Ladismith');
insert into test.towns (town_code, town_name) values ('CBM', 'Laingsburg');
insert into test.towns (town_code, town_name) values ('CBR', 'Montagu');
insert into test.towns (town_code, town_name) values ('CBS', 'Mossel Bay');
insert into test.towns (town_code, town_name) values ('CBT', 'Murraysburg');
insert into test.towns (town_code, town_name) values ('CBY', 'Piketburg');
insert into test.towns (town_code, town_name) values ('CCA', 'Prince Albert');
insert into test.towns (town_code, town_name) values ('CCC', 'Riversdale');
insert into test.towns (town_code, town_name) values ('CCD', 'Robertson');
insert into test.towns (town_code, town_name) values ('CCK', 'Swellendam');
insert into test.towns (town_code, town_name) values ('CCM', 'Tulbagh');
insert into test.towns (town_code, town_name) values ('CCO', 'Uniondale');
insert into test.towns (town_code, town_name) values ('CCP', 'Vanrhydorp');
insert into test.towns (town_code, town_name) values ('CEA', 'Moorreesburg');
insert into test.towns (town_code, town_name) values ('CEG', 'Heidelberg');
insert into test.towns (town_code, town_name) values ('CEM', 'Hermanus');
insert into test.towns (town_code, town_name) values ('CEO', 'Grabouw');
insert into test.towns (town_code, town_name) values ('CER', 'Bonnievale');
insert into test.towns (town_code, town_name) values ('CES', 'Albertina');
insert into test.towns (town_code, town_name) values ('CEX', 'Porterville');
insert into test.towns (town_code, town_name) values ('CEY', 'Strand');
insert into test.towns (town_code, town_name) values ('CFA', 'Wolseley');
insert into test.towns (town_code, town_name) values ('CFG', 'Vredenburg');
insert into test.towns (town_code, town_name) values ('CFM', 'Somerset West');
insert into test.towns (town_code, town_name) values ('CFP', 'Velddrif');
insert into test.towns (town_code, town_name) values ('CFR', 'Brackenfell');
insert into test.towns (town_code, town_name) values ('CCT', 'City of Cape Town Municipal');

insert into development.towns (town_code, town_name) values ('CA', 'Cape Town');
insert into development.towns (town_code, town_name) values ('CF', 'Kuils River');
insert into development.towns (town_code, town_name) values ('CG', 'Oudtshoorn');
insert into development.towns (town_code, town_name) values ('CJ', 'Paarl');
insert into development.towns (town_code, town_name) values ('CK', 'Malmesbury');
insert into development.towns (town_code, town_name) values ('CL', 'Stellenbosch');
insert into development.towns (town_code, town_name) values ('CN', 'Wellington');
insert into development.towns (town_code, town_name) values ('CO', 'Calitzdorp');
insert into development.towns (town_code, town_name) values ('CR', 'Hopefield');
insert into development.towns (town_code, town_name) values ('CT', 'Ceres');
insert into development.towns (town_code, town_name) values ('CV', 'Vredendal');
insert into development.towns (town_code, town_name) values ('CW', 'Worcester');
insert into development.towns (town_code, town_name) values ('CX', 'Knysna');
insert into development.towns (town_code, town_name) values ('CY', 'Bellville');
insert into development.towns (town_code, town_name) values ('CZ', 'Beaufort West');

insert into development.towns (town_code, town_name) values ('CAM', 'Caledon');
insert into development.towns (town_code, town_name) values ('CAR', 'Clanwilliam');
insert into development.towns (town_code, town_name) values ('CAW', 'George');
insert into development.towns (town_code, town_name) values ('CBL', 'Ladismith');
insert into development.towns (town_code, town_name) values ('CBM', 'Laingsburg');
insert into development.towns (town_code, town_name) values ('CBR', 'Montagu');
insert into development.towns (town_code, town_name) values ('CBS', 'Mossel Bay');
insert into development.towns (town_code, town_name) values ('CBT', 'Murraysburg');
insert into development.towns (town_code, town_name) values ('CBY', 'Piketburg');
insert into development.towns (town_code, town_name) values ('CCA', 'Prince Albert');
insert into development.towns (town_code, town_name) values ('CCC', 'Riversdale');
insert into development.towns (town_code, town_name) values ('CCD', 'Robertson');
insert into development.towns (town_code, town_name) values ('CCK', 'Swellendam');
insert into development.towns (town_code, town_name) values ('CCM', 'Tulbagh');
insert into development.towns (town_code, town_name) values ('CCO', 'Uniondale');
insert into development.towns (town_code, town_name) values ('CCP', 'Vanrhydorp');
insert into development.towns (town_code, town_name) values ('CEA', 'Moorreesburg');
insert into development.towns (town_code, town_name) values ('CEG', 'Heidelberg');
insert into development.towns (town_code, town_name) values ('CEM', 'Hermanus');
insert into development.towns (town_code, town_name) values ('CEO', 'Grabouw');
insert into development.towns (town_code, town_name) values ('CER', 'Bonnievale');
insert into development.towns (town_code, town_name) values ('CES', 'Albertina');
insert into development.towns (town_code, town_name) values ('CEX', 'Porterville');
insert into development.towns (town_code, town_name) values ('CEY', 'Strand');
insert into development.towns (town_code, town_name) values ('CFA', 'Wolseley');
insert into development.towns (town_code, town_name) values ('CFG', 'Vredenburg');
insert into development.towns (town_code, town_name) values ('CFM', 'Somerset West');
insert into development.towns (town_code, town_name) values ('CFP', 'Velddrif');
insert into development.towns (town_code, town_name) values ('CFR', 'Brackenfell');
insert into development.towns (town_code, town_name) values ('CCT', 'City of Cape Town Municipal');

insert into production.towns (town_code, town_name) values ('CA', 'Cape Town');
insert into production.towns (town_code, town_name) values ('CF', 'Kuils River');
insert into production.towns (town_code, town_name) values ('CG', 'Oudtshoorn');
insert into production.towns (town_code, town_name) values ('CJ', 'Paarl');
insert into production.towns (town_code, town_name) values ('CK', 'Malmesbury');
insert into production.towns (town_code, town_name) values ('CL', 'Stellenbosch');
insert into production.towns (town_code, town_name) values ('CN', 'Wellington');
insert into production.towns (town_code, town_name) values ('CO', 'Calitzdorp');
insert into production.towns (town_code, town_name) values ('CR', 'Hopefield');
insert into production.towns (town_code, town_name) values ('CT', 'Ceres');
insert into production.towns (town_code, town_name) values ('CV', 'Vredendal');
insert into production.towns (town_code, town_name) values ('CW', 'Worcester');
insert into production.towns (town_code, town_name) values ('CX', 'Knysna');
insert into production.towns (town_code, town_name) values ('CY', 'Bellville');
insert into production.towns (town_code, town_name) values ('CZ', 'Beaufort West');

insert into production.towns (town_code, town_name) values ('CAM', 'Caledon');
insert into production.towns (town_code, town_name) values ('CAR', 'Clanwilliam');
insert into production.towns (town_code, town_name) values ('CAW', 'George');
insert into production.towns (town_code, town_name) values ('CBL', 'Ladismith');
insert into production.towns (town_code, town_name) values ('CBM', 'Laingsburg');
insert into production.towns (town_code, town_name) values ('CBR', 'Montagu');
insert into production.towns (town_code, town_name) values ('CBS', 'Mossel Bay');
insert into production.towns (town_code, town_name) values ('CBT', 'Murraysburg');
insert into production.towns (town_code, town_name) values ('CBY', 'Piketburg');
insert into production.towns (town_code, town_name) values ('CCA', 'Prince Albert');
insert into production.towns (town_code, town_name) values ('CCC', 'Riversdale');
insert into production.towns (town_code, town_name) values ('CCD', 'Robertson');
insert into production.towns (town_code, town_name) values ('CCK', 'Swellendam');
insert into production.towns (town_code, town_name) values ('CCM', 'Tulbagh');
insert into production.towns (town_code, town_name) values ('CCO', 'Uniondale');
insert into production.towns (town_code, town_name) values ('CCP', 'Vanrhydorp');
insert into production.towns (town_code, town_name) values ('CEA', 'Moorreesburg');
insert into production.towns (town_code, town_name) values ('CEG', 'Heidelberg');
insert into production.towns (town_code, town_name) values ('CEM', 'Hermanus');
insert into production.towns (town_code, town_name) values ('CEO', 'Grabouw');
insert into production.towns (town_code, town_name) values ('CER', 'Bonnievale');
insert into production.towns (town_code, town_name) values ('CES', 'Albertina');
insert into production.towns (town_code, town_name) values ('CEX', 'Porterville');
insert into production.towns (town_code, town_name) values ('CEY', 'Strand');
insert into production.towns (town_code, town_name) values ('CFA', 'Wolseley');
insert into production.towns (town_code, town_name) values ('CFG', 'Vredenburg');
insert into production.towns (town_code, town_name) values ('CFM', 'Somerset West');
insert into production.towns (town_code, town_name) values ('CFP', 'Velddrif');
insert into production.towns (town_code, town_name) values ('CFR', 'Brackenfell');
insert into production.towns (town_code, town_name) values ('CCT', 'City of Cape Town Municipal');